return {
    terminal                   = "kitty",
    browser                    = "flatpak run com.brave.Browser",
    editor                     = "code",
    fileExplorer               = "thunar",
    audioSettings              = "pavucontrol",

    touchpadDisableTyping      = true,
    touchpadScrollFactor       = 0.3,
    gestureFingers             = 3,
    workspaceSwipeFingers      = 4,
    gestureFingersMore         = 4,

    blurEnabled                = true,
    blurSpecialWs              = false,
    blurPopups                 = true,
    blurInputMethods           = false,
    blurSize                   = 4,
    blurPasses                 = 1,
    blurXray                   = false,

    shadowEnabled              = false,
    shadowRange                = 15,
    shadowRenderPower          = 4,
    shadowColour               = "rgba(00000010)",

    workspaceGaps              = 2,
    windowGapsIn               = 3,
    windowGapsOut              = 4,
    singleWindowGapsOut        = 5,

    windowOpacity              = 0.93,
    windowRounding             = 6,
    windowBorderSize           = 1,
    activeWindowBorderColour   = "rgba(1793d1e6)",
    inactiveWindowBorderColour = "rgba(c8c5d111)",

    volumeStep                 = 5,
    volumeMax                  = 100,
    cursorTheme                = "Adwaita",
    cursorSize                 = 24,
    sleepGestureCmd            = "systemctl suspend-then-hibernate",

    kbMoveWinToWs              = "SUPER + SHIFT",
    kbMoveWinToWsGroup         = "CTRL + SUPER + ALT",
    kbGoToWs                   = "SUPER",
    kbGoToWsGroup              = "CTRL + SUPER",
    kbNextWs                   = "CTRL + SUPER + Right",
    kbPrevWs                   = "CTRL + SUPER + Left",

    kbWindowGroupCycleNext     = "ALT + TAB",
    kbWindowGroupCyclePrev     = "SHIFT + ALT + TAB",
    kbUngroup                  = "SUPER + U",
    kbToggleGroup              = "SUPER + Comma",

    kbMoveWindow               = "SUPER + Z",
    kbResizeWindow             = "SUPER + X",
    kbWindowPip                = "SUPER + ALT + backslash",
    kbPinWindow                = "SUPER + P",
    kbWindowFullscreen         = "SUPER + F",
    kbWindowBorderedFullscreen = "SUPER + ALT + F",
    kbToggleWindowFloating     = "SUPER + V",
    kbCloseWindow              = "SUPER + Q",

    kbSpecialWs                = "SUPER + Minus",
    kbSystemMonitorWs          = "CTRL + SHIFT + Escape",
    kbMusicWs                  = "SUPER + M",
    kbCommunicationWs          = "SUPER + D",
    kbTodoWs                   = "SUPER + R",

    kbTerminal                 = "SUPER + Return",
    kbBrowser                  = "SUPER + W",
    kbEditor                   = "SUPER + C",
    kbFileExplorer             = "SUPER + E",

    kbSession                  = "CTRL + ALT + Delete",
    kbShowSidebar              = "SUPER + N",
    kbClearNotifs              = "CTRL + ALT + C",
    kbShowPanels               = "SUPER + K",
    kbLock                     = "SUPER + SHIFT + X",
    kbRestoreLock              = "SUPER + ALT + L",
}
